### ISSUE TITLE
训练的inplace问题

### ISSUE THREAD

**Issue by yuymf** [ZYB0726/MKDNet#4]
纯萌新，试了改inplace=false，改+=，还是报错，不知道会不会是gan loss那块的问题，可以抽空帮忙看看么！！999
报错信息：贴了 torch.autograd.set_detect_anomaly(True)在下面（不是特别懂。。。）

[W python_anomaly_mode.cpp:104] Warning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "run_training.py", line 55, in <module>
    main()
  File "run_training.py", line 50, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 39, in run_training
    expr_func(settings)
  File "../ltr/train_settings/dimp/super_dimp.py", line 156, in run
    trainer.train(50, load_latest=True, fail_safe=True)
  File "../ltr/trainers/base_trainer.py", line 71, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 84, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 61, in cycle_dataset
    loss, loss_D, stats = self.actor(data)
  File "../ltr/actors/tracking.py", line 100, in __call__
    test_proposals=data['test_proposals'])
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "../ltr/models/tracking/dimpnet.py", line 148, in forward
    pred_fake_feat_G2 =self.feat_D2.forward(roi4t)
  File "../ltr/models/target_classifier/networks_d.py", line 45, in forward
    validity = self.model(img_flat)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
 (function _print_stack)

Training crashed at epoch 1
Traceback for the error!
Traceback (most recent call last):
  File "../ltr/trainers/base_trainer.py", line 71, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 84, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 70, in cycle_dataset
    loss.backward()
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by ZYB0726** [comment]
应该是pytorch版本有问题&nbsp; 我用的是pytorch1.4



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月20日(周日) 凌晨0:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZYB0726/MKDNet] 训练的inplace问题 (Issue #4)




 
纯萌新，试了改inplace=false，改+=，还是报错，不知道会不会是gan loss那块的问题，可以抽空帮忙看看么！！999
 报错信息：贴了 torch.autograd.set_detect_anomaly(True)在下面（不是特别懂。。。）
 
[W python_anomaly_mode.cpp:104] Warning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
 File "run_training.py", line 55, in 
 main()
 File "run_training.py", line 50, in main
 run_training(args.train_module, args.train_name, args.cudnn_benchmark)
 File "run_training.py", line 39, in run_training
 expr_func(settings)
 File "../ltr/train_settings/dimp/super_dimp.py", line 156, in run
 trainer.train(50, load_latest=True, fail_safe=True)
 File "../ltr/trainers/base_trainer.py", line 71, in train
 self.train_epoch()
 File "../ltr/trainers/ltr_trainer.py", line 84, in train_epoch
 self.cycle_dataset(loader)
 File "../ltr/trainers/ltr_trainer.py", line 61, in cycle_dataset
 loss, loss_D, stats = self.actor(data)
 File "../ltr/actors/tracking.py", line 100, in call
 test_proposals=data['test_proposals'])
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "../ltr/models/tracking/dimpnet.py", line 148, in forward
 pred_fake_feat_G2 =self.feat_D2.forward(roi4t)
 File "../ltr/models/target_classifier/networks_d.py", line 45, in forward
 validity = self.model(img_flat)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
 input = module(input)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
 return forward_call(*input, **kwargs)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
 return F.linear(input, self.weight, self.bias)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
 return torch._C._nn.linear(input, weight, bias)
 (function _print_stack)
 
Training crashed at epoch 1
 Traceback for the error!
 Traceback (most recent call last):
 File "../ltr/trainers/base_trainer.py", line 71, in train
 self.train_epoch()
 File "../ltr/trainers/ltr_trainer.py", line 84, in train_epoch
 self.cycle_dataset(loader)
 File "../ltr/trainers/ltr_trainer.py", line 70, in cycle_dataset
 loss.backward()
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
 File "/home/yuymf/anaconda3/envs/mkdnet/lib/python3.7/site-packages/torch/autograd/init.py", line 156, in backward
 allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
 RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuymf** [comment]
感谢回复，那可能是版本问题了，但1.7可以训练pytracking，如果要使用1.7跑的话，请问您能给点建议，要修改哪里比较好>_<
